Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,13 +18,14 @@ jobs:
     steps:
     - name: 'Trigger an Azure Pipeline to check if PR can be merged'
       id: azure-test
-      uses: Azure/pipelines@v1
+      uses: deppsu/azure-pipeline-github-action@v1.0.5
+      #uses: Azure/pipelines@v1
       with:
         azure-devops-project-url: 'https://dev.azure.com/priscofarina/Space%20Game'
         azure-pipeline-name: 'github-build-contribution' # name of the Azure pipeline to be triggered
         azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
         #azure-pipeline-variables:  '{"variable1": "value1", "variable2": "value2"}' # optional stringified json
-    - name: Check results
-      if: ${{ failure() }}
-      run: |
-        echo pipeline is failed ; exit 1       
+    #- name: Check results
+    #  if: ${{ failure() }}
+    # run: |
+    #    echo pipeline is failed ; exit 1       
